export const BATCH_INTERVAL_MS = 2
export const BATCH_SIZE = 30
export const MAX_POOL_COUNT = 150
export const NEW_POOL_AGE_THRESHOLD_MS = 3600 * 1000
export const TRENCH_LIMIT_NEW = 30
export const TRENCH_LIMIT_LOCKED = 60
export const TRENCH_LIMIT_SPENT = 30
export const CARD_HEIGHT_PX = 119
export const CARD_OVERSCAN_COUNT = 3
